language: python
python:
  - "3.8"
addons:
  apt:
    update: true
    packages:
      - pandoc
install:
  - pip install pytype==2021.3.10
  - pip install flake8==3.9.2
script:
  - make install lint-errors test nb-markdown
